#!/bin/bash

# Define variables for the command line arguments
R=8,
NUM_UNROLLED_STEPS=4
TRAIN_BATCH_SIZE=1
TEST_BATCH_SIZE=1
METRIC="val_psnr_scan"
slices=($(seq 0 16))
VARIANCES_LIST=$(IFS=,; echo "${slices[*]}")
VARIANCE_CALCULATION_METHOD="J_sketch"


printf "VARIANCES_LIST: $VARIANCES_LIST\n"
CONFIG_FILE="configs/mri-recon/fastmri-brain/templates/cg_unrolled.yaml"
MEDDLR_CACHE_DIR="/cache/meddlr"
MEDDLR_DATASETS_DIR="/data"
MEDDLR_RESULTS_DIR="/results_noise"

# Export the MEDDLR environment variables
export MEDDLR_CACHE_DIR
export MEDDLR_DATASETS_DIR
export MEDDLR_RESULTS_DIR

# Run the python command with the specified variables
python tools/eval_net.py \
--config-file $CONFIG_FILE \
--metric $METRIC \
MODEL.UNROLLED.NUM_UNROLLED_STEPS $NUM_UNROLLED_STEPS \
AUG_TEST.UNDERSAMPLE.ACCELERATIONS $R \
AUG_TRAIN.UNDERSAMPLE.ACCELERATIONS $R \
TEST.CALCULATE_PIXEL_VARIANCES True \
TEST.VARIANCES_LIST $VARIANCES_LIST \
SOLVER.TRAIN_BATCH_SIZE $TRAIN_BATCH_SIZE \
SOLVER.TEST_BATCH_SIZE $TEST_BATCH_SIZE \
TEST.VARIANCE_CALCULATION_METHOD $VARIANCE_CALCULATION_METHOD